### ISSUE TITLE
Pkgtools incompatible with Dash

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/MLFS-pkgtool#10]
Without bash, makepkg cannot make symbolic link creation script for packages.

**Comment by dslm4515** [comment]
For systems with out coreutils: `removepkg` needs `paste` from coreutils and `installpkg` need `numfmt` from coreutils
Also, pkgtools scripts rely on specific paramters that GNU findutils accepts.

**Comment by dslm4515** [comment]
Also pkgtools requires GNU Findutils for specific flags...otherwise, the links are never stored in the built txz package

**Comment by takusuman** [comment]
> For systems with out coreutils: `removepkg` needs `paste` from coreutils and `installpkg` need `numfmt` from coreutils Also, pkgtools scripts rely on specific paramters that GNU findutils accepts.

Depending on what these utilities do, we could rewrite them in Shell script functions.
Also, it would be more sane to port from GNU Bourne-Again to Korn Shell 93 instead of going to POSIX, since some features are impossible to mimick from Korn Shell/Bash to POSIX.

**Comment by dslm4515** [comment]
My copy of slackware pkgtool scripts are old... from 4-OCT-2018. I haven't checked Slackware since slackware 13.0 was released. As of today, Slackware is at version 15 with pkgtools last updated on 20-May-2021

I could update my pkgtool scripts... but  I would prefer to build my own scripts _based_ on slackware pkgtools.  I like using pkgtools as I can easily add/remove compiled packages and keep track of what file was installed by what package. I'll have the dependencies between packages handled by a script later in the future.

**Comment by dslm4515** [comment]
Issues I have with pkgtools:

- Hard coded paths for bash, du, etc.
- sed and grep commands are specific to GNU's sed & grep ...  heirloom-ng breaks the makepkg & installpkg scripts
- I cannot figure out how compiled packages are installed during setup... how do I build a new system by using packages I already compiled? I've tried and ended up with a broken system that needs `LD_LIBRARY_PATH` set

**Comment by dslm4515** [comment]
I might ... switch to [spkg](https://github.com/megous/spkg)

```
Dependencies
------------

  Judy >= 1.0.3         http://judy.sourceforge.net
  glib >= 2.2.1         general purpose C library
  popt >= 1.7           command line parser
  zlib >= 1.1.4         zlib (de)compression library
```

**Comment by takusuman** [comment]
> Issues I have with pkgtools:
> 
> * Hard coded paths for bash, du, etc.
> * sed and grep commands are specific to GNU's sed & grep ...  heirloom-ng breaks the makepkg & installpkg scripts
> * I cannot figure out how compiled packages are installed during setup... how do I build a new system by using packages I already compiled? I've tried and ended up with a broken system that needs `LD_LIBRARY_PATH` set

I think I could fix that, for fun.

**Comment by takusuman** [comment]
> I might ... switch to [spkg](https://github.com/megous/spkg)
> 
> ```
> Dependencies
> ------------
> 
>   Judy >= 1.0.3         http://judy.sourceforge.net
>   glib >= 2.2.1         general purpose C library
>   popt >= 1.7           command line parser
>   zlib >= 1.1.4         zlib (de)compression library
> ```

That seems a good catch too.

**Comment by takusuman** [comment]
> For systems with out coreutils: `removepkg` needs `paste` from coreutils and `installpkg` need `numfmt` from coreutils

By the way, ``paste`` is specified in POSIX, apparently --- and [Heirloom NG has it](https://github.com/Projeto-Pindorama/heirloom-ng/tree/master/paste) --- so, in the worst case, the most basic UNIX toolset for Linux would have it.
``numfmt`` can be **theorically** replaced by some Shell hacks.

**Comment by dslm4515** [comment]
Closing issue as I dropped pkgtools for spkg. Development has begun in [spkg-duo](https://github.com/dslm4515/MLFS-pkgtool/tree/spkg-duo) branch
